name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      # FRONTEND
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd front
          npm install

      - name: Run frontend tests
        run: |
          cd front
          npm test -- --watchAll=false

      # BACKEND
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install backend dependencies
        run: |
          cd back
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd back
          source env.sh
          pytest


  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build React
        run: |
          cd front
          npm install
          npm run build
