name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      # FRONTEND
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: |
          cd front
          npm install

      - name: Run frontend tests
        run: |
          cd front
          npm test -- --watchAll=false

      # BACKEND
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install backend dependencies
        run: |
          cd back
          pip install -r requirements.txt

      - name: Run backend tests
        run: |
          cd back
          source env.sh
          pytest


  deploy-frontend:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build React
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy to EC2 Frontend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "front/*"
          target: ${{ secrets.FRONTEND_PATH }}

      - name: Restart Frontend Service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            npm install -g serve
            serve -s build -l 3000


  deploy-backend:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy Backend
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "back/*"
          target: ${{ secrets.BACKEND_PATH }}

      - name: Install dependencies and restart API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_BACKEND_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ${{ secrets.BACKEND_PATH }}
            pip3 install -r requirements.txt
            sudo systemctl restart fastapi
